CREATE_USER_TABLE_QUERY = '''
        CREATE TABLE IF NOT EXISTS telegram_bot_users
        (ID INTEGER PRIMARY KEY,
        TELEGRAM_ID INTEGER,
        USERNAME CHAR(50),
        FIRST_NAME CHAR(50),
        LAST_NAME CHAR(50),
        REFERRAL_LINK TEXT NULL,
        UNIQUE (TELEGRAM_ID)
        )
'''

CREATE_USER_FORM_TABLE_QUERY = """
    CREATE TABLE IF NOT EXISTS user_form
    (ID INTEGER PRIMARY KEY,
    TELEGRAM_ID INTEGER,
    NICKNAME CHAR(50),
    BIO TEXT,
    AGE INTEGER,
    OCCUPATION TEXT,
    MARRIED CHAR(50),
    PHOTO TEXT,
    UNIQUE (TELEGRAM_ID)
    )
"""

CREATE_REFERRAL_SYSTEM_TABLE_QUERY = """
    CREATE TABLE IF NOT EXISTS referral_system
    (ID INTEGER PRIMARY KEY,
    OWNER_TELEGRAM_ID INTEGER,
    REFERRAL_TELEGRAM_ID INTEGER,
    UNIQUE (OWNER_TELEGRAM_ID, REFERRAL_TELEGRAM_ID)
    )
    """

INSERT_USER_QUERY = '''INSERT OR IGNORE INTO telegram_bot_users VALUES (?, ?, ?, ?, ?, ?)'''

INSERT_USER_FORM_QUERY = """INSERT OR IGNORE INTO user_form VALUES (?,?,?,?,?,?,?,?)"""

SELECT_USER_QUERY = """SELECT * FROM telegram_bot_users WHERE TELEGRAM_ID = ?"""

SELECT_USER_FORM_QUERY = """SELECT * FROM user_form WHERE TELEGRAM_ID = ? """

SELECT_ID = """SELECT TELEGRAM_ID FROM telegram_bot_users WHERE USERNAME = ?"""

UPDATE_USER_LINK_GENERATION_QUERY = """
UPDATE telegram_bot_users SET REFERRAL_LINK = ? WHERE TELEGRAM_ID = ?
"""

INSERT_REFERRAL_USER_QUERY = """INSERT INTO referral_system VALUES (?,?,?)"""

SELECT_OWNER_BY_LINK_QUERY = """
SELECT TELEGRAM_ID FROM telegram_bot_users WHERE REFERRAL_LINK = ?
"""

SELECT_LIST_REFERRAL_BY_OWNER_ID_QUERY = """
SELECT REFERRAL_TELEGRAM_ID FROM referral_system WHERE OWNER_TELEGRAM_ID = ?
"""